#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to

#Start nbinx
nohup $OPENSHIFT_DATA_DIR/sbin/nginx >> $OPENSHIFT_DIY_LOG_DIR/server.log 2>&1 &

cd ~/app-root/data/perl-new/bin

#Development Server
#nohup ./perl $OPENSHIFT_REPO_DIR/MyApp/script/myapp_server.pl -r -p 15000 -h $OPENSHIFT_DIY_IP  >> $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &

#FastCGI
nohup ./perl $OPENSHIFT_REPO_DIR/MyApp/script/myapp_fastcgi.pl --listen $OPENSHIFT_DIY_IP:15000  >> $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &
